local_cache = "~/data/cdc-consumer/mysql80"

[database]
ip_or_host = "localhost"
port = 3306
user = "root"
password = "root"

[filters]
exclude_dbs = ["mysql", "sys"]

[fluvio]
topic = "rust-mysql-cdc"